[project]
name = "smolagents-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.15.0",
    "gradio-client>=1.7.0",
    "smolagents[openai]>=1.8.0",
]
